version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_web
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: fastapi_worker
    command: celery -A celery_worker.celery_app worker --loglevel=info -P solo
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis

  beat:
    build: .
    container_name: fastapi_beat
    command: celery -A celery_worker.celery_app beat --loglevel=info
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6380"
